dailyPriceIncrease: '80'
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - refresh
          - busrefresh
          - busenv
          - prometheus
springdoc:
  show:
    actuator: true
spring:
  sleuth:
    baggage:
      remote-fields: x-user-id
      tag-fields: x-user-id
